# Generated by Django 2.2.17 on 2022-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20220602_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='top_level_domain',
        ),
        migrations.AddField(
            model_name='country',
            name='top_level_domain',
            field=models.ManyToManyField(to='countries.Domain'),
        ),
    ]
